### ISSUE TITLE
German listing doesn't show year

### ISSUE THREAD

**Issue by djdembeck** [seanap/Audiobooks.bundle#20]
> I don't know whether it's the german audible page but I don't see any years.
> Will do some further testing and report back.

![grafik](https://user-images.githubusercontent.com/16120882/130750786-c386f628-9b71-4cae-b45e-463c89e46cbb.png)

_Originally posted by @rabelux in https://github.com/seanap/Audiobooks.bundle/issues/10#issuecomment-905272979_

**Comment by rabelux** [comment]
Really appreciate your efforts!
I updated to the latest version (v2021.09.02.1) and I can't reproduce the error as I don't get any matches anymore.

If I change the website to audible.com I do get a match but only on the first popup after klicking "fix match". If I go to "search options" and search again (with unchanged title) there are no results. 
Screenshot of what I'm talking about:
![grafik](https://user-images.githubusercontent.com/16120882/132142653-2446c09d-63da-4e51-96b2-42e607c84e64.png)

Screenshot after klicking "fix match" with webiste set to "audible.com":
![grafik](https://user-images.githubusercontent.com/16120882/132142687-af00c30c-f2e8-446f-b462-8a555a633425.png)

Logs:
[com.plexapp.agents.audiobooks.log](https://github.com/seanap/Audiobooks.bundle/files/7112421/com.plexapp.agents.audiobooks.log)

Let me know if you need more information. Thanks!

**Comment by rabelux** [comment]
This is the book I used for testing:
- [Panaray on audible.com](https://www.audible.com/search?keywords=panaray&ref=a_search_t1_header_search)
- [Panaray on audible.de](https://www.audible.de/search?keywords=panaray&ref=a_search_t1_header_search)

I noticed that the german page causes `ValueError: month must be in 1..12` and the US version `TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'` to point out the obvious parts.

**Comment by cutzenfriend** [comment]
I have the same issue. I also don't get matches anymore with the newest Version and german site.

Also the release date is always synced to 01-01-YEAR. The year is the correct year but day and month is always 01-01 :(

**Comment by djdembeck** [comment]
This looks to be caused by other countries listing their date in varying formats (or rather, North America listing theirs differently than the world). I should be able to write a quick fix for this sometime this week.

**Comment by djdembeck** [comment]
Please try the develop branch and report back any further issues you see with it.

**Comment by rabelux** [comment]
The date seems to be parsed correctly.
Unfortunately now I'm seeing this:
```
CRITICAL (agentkit:1018) - Exception in the search function of agent named 'Audiobooks', called with keyword arguments {'parentID': '199249', 'year': '2020', 'id': '199250', 'name': 'Die Wikinger', 'parentGUID': 'local://199249'} (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-2b1b51db9/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1011, in _search
    agent.search(*f_args, **f_kwargs)
  File "/mnt/Flash/PLEX/Library/Application Support/Plex Media Server/Plug-ins/Audiobooks.bundle/Contents/Code/__init__.py", line 192, in search
    info = self.run_search(search_helper, result)
  File "/mnt/Flash/PLEX/Library/Application Support/Plex Media Server/Plug-ins/Audiobooks.bundle/Contents/Code/__init__.py", line 440, in run_search
    self.score_result(f, helper, i, info, valid_itemId, year)
  File "/mnt/Flash/PLEX/Library/Application Support/Plex Media Server/Plug-ins/Audiobooks.bundle/Contents/Code/__init__.py", line 476, in score_result
    score = INITIAL_SCORE - sum_scores(all_scores)
  File "/mnt/Flash/PLEX/Library/Application Support/Plex Media Server/Plug-ins/Audiobooks.bundle/Contents/Code/__init__.py", line 474, in <lambda.1>
    sum_scores=lambda numberlist:reduce(lambda x,y:x+y,numberlist,0)
  File "/mnt/Flash/PLEX/Library/Application Support/Plex Media Server/Plug-ins/Audiobooks.bundle/Contents/Code/__init__.py", line 474, in <lambda.2>
    sum_scores=lambda numberlist:reduce(lambda x,y:x+y,numberlist,0)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by djdembeck** [comment]
I merged a fix also for the first error (great catch) if you want to go ahead and test from master/develop.

the `cannot read model` errors are common for 3rd party Plex plugins and are not something we can fix unfortunately.

**Comment by rabelux** [comment]
Will do 👏

**Comment by rabelux** [comment]
No more errors so far. I'd say this issue can be closed.

**Comment by cutzenfriend** [comment]
> Also the release date is always synced to 01-01-YEAR. The year is the correct year but day and month is always 01-01 :(

This issue is still there. For the release date in Plex only the date is correct.

![Comparison](https://i.imgur.com/ao91p9q.jpeg)

Audible: 17.12.2019
Plex after sync: 2019-01-01 --> should be 2019-12-17

**Comment by cutzenfriend** [comment]
> Are you preferring local metadata? I'm guessing that's due to Mp3Tag only storing the year in the tags. The metadata agent shows correct dates - at least in the logs.

You are correct - Thank you! When preferring Audible it works as expected.
